### ISSUE TITLE
"Something went wrong" error on ph and temperature tabs

### ISSUE THREAD

**Issue by mtorzews** [reef-pi/reef-pi#1352] opened 2021-01-15 20:15 UTC
Website error on iPhone when opening details of temp or pH on their respective tabs.  Error occurs in portrait mode. If in landscape mode on the phone it does not occur. No error on laptop.

**Comment by chrisleavoy** [comment] 2021-01-15 20:19
I have the same issue with Chrome on my iPhone. Thanks for tip it works in landscape! Attached screenshot. 

`TypeError: undefined is not an object (evaluating 't.length')

**Comment by chrisleavoy** [comment] 2021-01-15 20:20
![E32E4AFE-2580-4607-971F-DAC6BB9CA86B](https://user-images.githubusercontent.com/1428245/104774780-42cca580-5745-11eb-8b1c-251b61e65f94.png)

**Comment by mtorzews** [comment] 2021-01-15 20:21
yes, this is the same error I have.

**Comment by ranjib** [comment] 2021-08-07 22:10
Hi, 
i am not able to reproduce this error. Im trying with 4.2 build. can you retest. if this issue still exist, then please share more details like drivers and connectors. enough for us to be able to reproduce this so that we can fix it

**Comment by ranjib** [comment] 2021-08-17 16:03
Hi,
i was able to reproduce this and fix it in master. The fix will be released in 4.3

**Comment by ranjib** [comment] 2021-08-17 16:04
https://github.com/reef-pi/reef-pi/pull/1524

**Closed by ranjib** 2021-08-17 16:03 UTC
