### ISSUE TITLE
Was just thinking a flow sensor readout would be a good addition.

### ISSUE THREAD

**Issue by frazion** [reef-pi/reef-pi#1195] opened 2020-07-30 21:04 UTC
**Describe the solution you'd like**
The ability to query a flow sensor or multiple sensors would be great!

**Comment by ranjib** [comment] 2020-09-22 07:38
Do you have any specific sensor in mind. This will involve developing a specific driver that will use a gpio (inlet) to count the flow sensor pulse, if i understand correctly. I am open to review and incorporate the driver, but i doubt i'll have time to implement it any time soon.

**Comment by ranjib** [comment] 2020-09-22 08:16
This is a duplicate of https://github.com/reef-pi/reef-pi/issues/1106 , closing this. we'll use the older  issue for tracking. Thank you for taking the time to write down this feature requirement. Please use the other issue to share any insights or concerns.

**Closed by ranjib** 2020-09-22 08:16 UTC
Labels: duplicate, enhancement
