### ISSUE TITLE
Pi 3 B v1.2 PWM only work on initial setup reef-pi 4.3

### ISSUE THREAD

**Issue by Ren108** [reef-pi/reef-pi#1594] opened 2021-10-12 22:29 UTC
If i set up a new raspbian system and install reef-pi, all works like it should. After reboot the led is on and switches off, as soon as i try to dim it in manual mode. Same thing if i programm something to happen short after the reboot. The led is on until it should switch lightning level. Then it just switches off. I even tryed some older versions right down to 4.0 but always the same thing...

**Comment by ranjib** [comment] 2021-10-15 06:27
this means reef-pi the software (and kernel ) is working fine. This is related to circuit/hardware. I'll recommend isolating the pi from the rest and probing the gpio pins directly with multimeter, this will indicate if the problem is coming from pi itself or the circuit outside pi.

Since this is not a software issue, Im closing this. Use a build thread in reef2reef for help with  all thing build related.

**Closed as completed by ranjib** 2021-10-15 06:27 UTC
Labels: waiting-for-response
