### ISSUE TITLE
Temperature spikes

### ISSUE THREAD

**Issue by ykri** [reef-pi/reef-pi#1831] opened 2022-05-08 09:15 UTC
I get spikes in tank temperature. ![image](https://user-images.githubusercontent.com/16511588/167289638-763b12f8-7fe6-4d9d-8000-5cd470905aee.png)

**Comment by ranjib** [comment] 2022-05-16 05:54
this is a sensor error, likely due to faulty circuit or sensor. We have seen similar issues before. I am thinking of putting some kind of safety measure to discard this type of erroneous readings. Probably by applying some threshold...

**Comment by ranjib** [comment] 2022-06-30 06:50
@ykri thoughts?

**Comment by ykri** [comment] 2022-06-30 19:26
Hi @ranjib , didn't have a chance to replace the sensor in case there's something wrong with it. About the cable and connector I am using the same one I had with my previous diy controller (iAqua) and I never had any spikes like these. 

I'll wait for the workaround you mentioned if you manage to include it in your next version 

Y.

**Comment by ranjib** [comment] 2022-07-10 10:10
I do not have any immediate plans for a smoothing function for temperature module specifically. ph module provides a transformer function that might be useful for this, and in future ph/temperature module will be combined into one. Closing this since im not taking any itemized work from this. sensor issues are a common reliability risks, i suggest setting up alerts and replace them/address the cause if these are systemic. For sporadic cases, this should not cause any significant issue (since these are transient).

**Closed by ranjib** 2022-07-10 10:10 UTC
Labels: waiting-for-response
