### ISSUE TITLE
Suggestion: Add an ability to enable/disable timers

### ISSUE THREAD

**Issue by rryerson-ps** [reef-pi/reef-pi#711] opened 2019-01-31 03:56 UTC
As a user it would be useful to disable and then re-enable timers in order to perform maintenance on the associated equipment.

**Comment by ranjib** [comment] 2019-02-02 23:09
reef-pi does allow enabling/disabling timers. You can check the ui, theres a field name "enabled" that you can toggle to enable/diable the timer

**Comment by zekth** [comment] 2019-02-10 16:30
Maybe duplicate of #724 

Closing.

**Closed by zekth** 2019-02-10 16:30 UTC
Labels: invalid
