### ISSUE TITLE
Triger macro with Timer

### ISSUE THREAD

**Issue by liwajaya** [reef-pi/reef-pi#1452] opened 2021-05-14 14:53 UTC
Timer triggering a macro =
Version 4.1
 trigger macro with timer does not work.  The "reversed" button must be selected and then it works normally.  but it works backwards😭

**Comment by chrispo1** [comment] 2021-06-03 19:58
For me, I cannot get timers to execute a macro regardless.

FillTopOff Macro = 1 action turn on Ato FillTopOff Tried with Reversed/Normal

Ato FillTopOff is off and tested working.

Timer set to run macro FillTopOff at 15:00

Ato FillTopOff is never turned on

**Comment by ranjib** [comment] 2021-07-27 09:11
Timers require macros to be reversible. This is as expected.
When invoked in reverse mode , macro steps are executed in backward fashion. This is also expected behavior.
Can you share specifics of your issue, if its not doing what is expected

**Comment by ranjib** [comment] 2021-08-12 07:57
Hi, I am closing this since i am not taking any action items (bug or feature request). Please verify the setup with 4.2 release. I have tested timer and macro integration and was not able to reproduce this. There were several macro improvements made in 4.2, please let us know if this is still an issue, and if so provide details (driver, connector, equipment etc)

**Closed by ranjib** 2021-08-12 07:57 UTC
Labels: not-triaged
