### ISSUE TITLE
Kesa State Not Updating

### ISSUE THREAD

**Issue by roolimited** [reef-pi/reef-pi#1174] opened 2020-06-17 08:22 UTC
I've been playing with the HS300 and HS110 smart plugs to allow me to remove the need for having the power relay set up.

Everything is working at it should, however, It seems that the reef-pi doesn't periodically check the state of the outlets so when I turn the outlet off either via voice command (google home) or manually using the plug button, it doesn't update on the controller. 

Example: I turn plug 1 off manually using the switch, reef pi still thinks it's turned on.

**Comment by ranjib** [comment] 2020-08-01 23:48
This is the expected behavior. reef-pi does not poll Kasa outlets due to performance and portability reasons. If users or any external entity changes smart outlet state, reef-pi's known status will go out of sync. 
In most control situation this has not been an issue since equipment are syned every few often. This issue is very visible when equipment are manually controlled via UI and via other entities (human ) at the same time.

I am closing this ticket, since I don't intend to work on this, and its a known/expected behavior. Thank you for raising this, and let me know if you have question or feel free to reopen this ticket if you want bring up some other cases for which we should re-consider this.

**Closed by ranjib** 2020-08-01 23:48 UTC
Labels: bug
