### ISSUE TITLE
ATO - Check frequency for starting pump - another frequency for stopping pump

### ISSUE THREAD

**Issue by JimmyKer** [reef-pi/reef-pi#1246] opened 2020-10-08 09:51 UTC
### In the ATO configuration:
There is one sensor that determinates the water level, when water level is too low, the pump is activated until the sensor is un-triggered.

Reef-pi checks the sensor every xx seconds, and this is variable in the ATO Configuration.

### Issue:
When I now set the frequency time to 120 seconds, the pumps start when water level is too low, but will flood my sump because the next time the sensor is checked is 120 seconds later.

In my scenario I’ve set the frequency to 10 seconds, and this is already a trade-off between "not using too much CPU resources" and "flooding the input sensor".

### Proposal:
I believe it would be better having a **second frequency** check during the time the pump is activated.
_For example check sensor every 120 seconds for starting the pump, once started check the sensor every 1 second for stopping the pump._

**Comment by ranjib** [comment] 2021-12-28 10:07
Closing this as duplicate of https://github.com/reef-pi/reef-pi/issues/1696 . i think this is already possible with the recent improvements across timers and macros. but we have to test it out. lets continue this discussion on the other ticket

**Closed by ranjib** 2021-12-28 10:07 UTC
Labels: enhancement, proposal
