### ISSUE TITLE
[Request] cant find sht31-d. 

### ISSUE THREAD

**Issue by Yyov** [reef-pi/reef-pi#1147] opened 2020-05-13 07:20 UTC
I added sht31-d 3.3V and GND on board. Conected SCL , SDA

I would like to add this to reef-pi it would be posible with PH module but i can only add analog inputs in PH module. In config , connectors i can not find any analoge conections.

when using command promp i can find a connection when using code
I2cdetect -y 1 i detect a connection on 44.

Keep in mind i am a total noob in programming..

**Comment by ranjib** [comment] 2020-05-19 06:42
sht31d driver was added very recently and still not released yet. It will be release in the very next release. Once the public release is available, you can add it as a standard HAL driver (configuration -> drivers -> new) . Once added, the new driver will expose two pins (0 for temperature and 1 for humidty) that can be associated with analog input connectors and then the values can be monitored or used for controlling any equipment via the pH module. I'll be closing this ticket since this is not a bug or feature request. Let us know if you encounter any bug with the new release (will be out in an hour or so)

**Closed by ranjib** 2020-05-19 06:42 UTC
Labels: enhancement

**Comment by Yyov** [comment] 2020-05-23 12:30
hello @ranjib ,

I installed new update. Andset everything up. 
i can not seem to get a reading on ether the temp or humidity;
I get the error :
{"error":"stats for id: '2' not found"} | HTTP 404 
{"error":"stats for id: '1' not found"} | HTTP 404

when i sellect the option: ph status activated.

and 
{"error":"write /dev/i2c-1: remote I/O error"} | HTTP 404
when i sellect the option : ph status inactiv
i dubble checked the wiring and this seems fine.

Also double checked the adress of the sensor, i get a sensor on adres 44. next to the SHT31-D i only have 1 digital temperature sensor on there.

**Comment by ranjib** [comment] 2020-05-25 07:06
As I explained in the r2r thread. Use decimal address.
