### ISSUE TITLE
reef-pi 4.3 PWM only work on initial setup

### ISSUE THREAD

**Issue by Ren108** [reef-pi/reef-pi#1598] opened 2021-10-15 20:41 UTC
PWM only works after initial setup (testet with osci) after reboot changing the pwm frequency causes the pwm pin to just stop working.
How to reprodurce: (testet on Pi 3b and 3b+): Get newest raspbian image, update and install reef-pi, define pwm ports 0 and 1, reboot and change pwm frequency.
How to solve: disable reef-pi from autostarting and start it by yourself.

Like i said in my other issue i opened, its NOT hardwarerelatet.

**Comment by schwabix-1311** [comment] 2021-10-18 19:13
Can you check for duplicate port assignments, e.g. same HW pin used as an gpio output and for PWM? This may not be obvious, as the numbering for each differs.
Other than that I can confirm it does work here (after resolving exactly such a conflicting assignment) ...

**Comment by ranjib** [comment] 2021-11-03 07:19
we can isolate if the bug is coming from reef-pi software or linux.  Just cat these two files at the points where you can observe PWM is not happening correctly
```
root@raspberrypi:cat /sys/class/pwm/pwmchip0/pwm0/duty_cycle 
root@raspberrypi:cat /sys/class/pwm/pwmchip0/pwm0/period
```
if these values are wrong, then we know its reef-pi issue. If they are correct, then reef-pi did its job correctly, and its something else, but kernel got our requested values

**Comment by Ren108** [comment] 2021-11-03 21:19
period is 10000000 and duty_cycle changes with the value in webinterface.
I think it has something to do with the boot order. I read something about boot order and pwm problems on raspi.

**Comment by Ren108** [comment] 2021-12-04 23:31
Short update: just tested that version on raspberry lite and it works like it should.

**Comment by ranjib** [comment] 2021-12-28 10:28
im closing this since i am not able to reproduce it in pi zero or pi 2 and I think the issue is beyond reef-pi. reef-pi only configures the kernel, if there's a problem from there on, reef-pi will not be able to detect it.

**Comment by ranjib** [comment] 2021-12-28 10:28
feel free to reopen if you want to discuss further or have any question

**Closed by ranjib** 2021-12-28 10:28 UTC
