### ISSUE TITLE
Can We make the configuration page link to github open a new tab automatically instead of using the current tab.

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1335] opened 2021-01-01 19:15 UTC
Really just a pet peave of mine but if it did it automatically instead of using the current tab that would be awesome.

**Comment by ranjib** [comment] 2021-01-02 19:33
reef-pi is based on react, which is famous for single-page apps. Single page apps do not open tabs/links by design and I kinda feel it's nicer than hyperlinked apps. This also has significant implications in mobile/ipad like devices where the single page app gives a proxy feeling of native apps. 
Sorry @gminton86 , I'm closing this as well, since I wont be doing any code changes for this. If this becomes way too annoying for more folks, we can think of a dedicated config UI link that users can directly use (e.g. HTTP://<reef-pi-ip>/config)

**Closed by ranjib** 2021-01-02 19:33 UTC
