### ISSUE TITLE
Not able to add Lights graph to dashboard

### ISSUE THREAD

**Issue by flokstra** [reef-pi/reef-pi#1055] opened 2020-02-24 10:34 UTC
**Describe the bug**
I am not able to select the lights graph when configuring the dashboard. When selecting Light it just defaults to Health. Happens in all  browsers on all devices and i do not get any errors in the chrome developer console.

**To Reproduce**
1. Go to 'dashboard'
2. Click on 'configure'
3. Under 'Graphs' open a pulldown menu and select 'Light'
4. Selection defaults to 'Health' 
5. click 'Update' -> Nothing happens

**Expected behavior**
I expect the Light option to be selection and on Update to be added to that particular Graphs section.

**Desktop (please complete the following information):**
 - Device: Pi3 B+
 - reef-pi version 3.2
 - Browser MacOs: Safari & Chrome, iOs (ipad and iphone): Safari

**Comment by ranjib** [comment] 2020-03-05 09:49
This is not a bug, It is as intended and not done due to time/resource constrain. We have a list of features and I prioritized this lower as it requires more work. And impact is only aesthetics. For dashboard we have to generate the light curve upfront (pre compute) . With so many different profiles this is a lot of work. We plan to ship this in piecemeal, but i;ll still consider this as an enhancement.  Note, reef-pi does emit the current channel values as metrics, so you can use adafruit.io or prometheus/grafana to make the light charts (and its arguably more reliable). Im closing this as we intend to ship this per profile basis. Currently auto (or fixed interval) profile shows chart. I am thinking of adding fixed, diurnal and sine profile in 4.0.

**Closed by ranjib** 2020-03-05 09:49 UTC
Labels: enhancement
