### ISSUE TITLE
temperature sensor going to -1

### ISSUE THREAD

**Issue by crashbash2020** [reef-pi/reef-pi#2086] opened 2023-07-20 00:04 UTC
Hi,

im having a problem with my temperature sensors faulting out every ~3-4 days. 

i noted the logs mention 2 errors, one for each temperature sensor:

````temperature sub-system. Failed to read sensor 450LWATER. Error:open /sys/bus/w1/devices/28-03079779ab73/w1_slave: no such file or directory````

````temperature sub-system. Failed to read sensor AirTemperature. Error:open /sys/bus/w1/devices/28-0308977936ed/w1_slave: no such file or directory````

A quick google shows the error can be a sign the probe is failing/shorting, I did check my sensor and there was a little water inside so I have replaced with a new one that is fully sealed. the error still persists.

the system was stable for about ~3 years before this so i doubt its software related, more likely hardware. I was hoping someone could point me in the direction to begin troubleshooting (is there a more verboose logging?) given both are faulting out I assume its faulting the entire section related to temperature. So far only a hard reset of the power to the unit fixes it until it happens again.

cheers

**Comment by ranjib** [comment] 2023-09-05 08:57
this indicates the problem is below reef-pi.  Mostly a physical hardware (bad probe, bad connection/circuir, corrosion, pi being under voltage etc)  . My probe failed almost after evert 2-3 years. Only a handful have survived more than 4 -5 years. I feel DS18b20 probe quality varies a lot,

**Comment by ranjib** [comment] 2023-09-05 08:59
I am closing this as this is not a reef-pi software issue, I believe, feel free to reopen if you want to discuss further

**Closed by ranjib** 2023-09-05 08:59 UTC
