### ISSUE TITLE
Temperature sensor failure. Error:read /sys/bus/w1/devices/28-03189779a648/w1_slave: interrupted system call

### ISSUE THREAD

**Issue by clownfish44** [reef-pi/reef-pi#1175] opened 2020-06-21 21:32 UTC
Temperature sensor failure. Error:read /sys/bus/w1/devices/28-03189779a648/w1_slave: interrupted system call

happens on version 3.4

**Comment by roolimited** [comment] 2020-06-23 06:26
I get this as well. It's been picked up on R2R. Ranjib is aware it's happening with 3.4 over there. Some users have downgraded to 3.3 to test and the issue goes away.. No update on when this will be fixed though.

**Comment by sandormaracsko** [comment] 2020-09-02 16:20
I also get the same error about 3-6 times a day:
Error log: temperature sub-system. Failed to read sensor air. Error:read /sys/bus/w1/devices/28-0306979438c8/w1_slave: interrupted system call

Email sent by system:
Temperature sensor failure. Error:read /sys/bus/w1/devices/28-0306979438c8/w1_slave: interrupted system call
(version 3.4)

**Comment by ranjib** [comment] 2020-11-10 07:38
Hi folks,
is this still happening with 3.5 as well? I have not encountered this yet and was not able to reproduce it. We have introduced retry logic which we think will address this, but hard to test from our end. Im closing this since we dont have any other action item on this. Please feel free to reopen if this is still an issue and the retry (>3.5) is not fixing it

**Closed by ranjib** 2020-11-10 07:38 UTC

**Comment by sandormaracsko** [comment] 2020-11-10 08:22
Hi Ranjib,
Thanks for the v3.5 since then I have not experienced it happening.
Many thanks,
Sandor

------ Original Message ------
