### ISSUE TITLE
Temperature graph oddities and improvements

### ISSUE THREAD

**Issue by ALPHAB3TS00P** [reef-pi/reef-pi#292] opened 2018-01-13 01:35 UTC
![image](https://user-images.githubusercontent.com/15350027/34901350-750f1302-f7c6-11e7-965b-516436a46e35.png)

![image](https://user-images.githubusercontent.com/15350027/34901375-a8ec39f2-f7c6-11e7-816e-e416cf58328b.png)

Not sure if it is what data type you are using (float might cause issues) or if there is some odd rounding happening but I'm seeing some strange things on the temperature graph. see attached pictures. 

Also if we are graphing from a list maybe we can do some better scaling and use more of the screen real-estate for visualizing the graph

**Comment by ranjib** [comment] 2018-01-13 04:58
Thank you for reporting this bug. 
What version  of reef-pi you are using?
The first issue is happening due to the default Y axis range in temperature chart being set to 76 to 82F. I intend to make this customizable as part of bigger customizable  dashboard work. I'll keep this open till that work is done.
I think I have fixed the second bug recently. This used to happen due to floating point calculation. It should not happen with 1.1 release. If this is not the case, let me know

**Comment by ALPHAB3TS00P** [comment] 2018-01-13 06:09
I'm using 1.1 for the pi 0

**Comment by ranjib** [comment] 2018-01-13 06:49
Thats strange, because I just verified we had this issue, and I have specific code now in place that makes the readings two decimal 
https://github.com/reef-pi/reef-pi/blob/1.1/controller/temperature/control.go#L97
and
https://github.com/reef-pi/reef-pi/blob/1.1/controller/temperature/controller.go#L43
This should consistently return two decimal values for temperature readings.
 I'll  try to reproduce this.  I am not able to see this any of my 1.1 based controllers

**Comment by ALPHAB3TS00P** [comment] 2018-01-13 19:30
![image](https://user-images.githubusercontent.com/15350027/34909413-94736ef4-f85d-11e7-908f-3204f8a3cbdf.png)

**Comment by ranjib** [comment] 2018-05-04 01:31
limit precision to two decimal only: https://github.com/reef-pi/reef-pi/pull/346
temp chart dimension fix: https://github.com/reef-pi/reef-pi/pull/338
ability to specify custom chat min and max: https://github.com/reef-pi/reef-pi/pull/335

These fixes will be released as part of 2.0, and together they addresses all the issues mentioned here

**Closed by ranjib** 2018-05-04 01:31 UTC
Labels: bug
